server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2db?useSSL=false
    username: root
    password: root123
#    driver-class-name: com.mysql.jdbc.Driver
    
#    tomcat:
#     test-while-idle: true
#     validation-query: SELECT 1
#    initialization-mode: never
#    platform: mysql

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none 
check-user-scopes: true